# Generated by Django 4.1.6 on 2023-02-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isadmin',
        ),
    ]
