# Generated by Django 4.1.6 on 2023-02-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('location_lon', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
            ],
        ),
    ]
