# Generated by Django 4.1.6 on 2023-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_skill_event_required_skill_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
